spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8010


# mybatis 打印 sql 日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl